package Entities;
// Generated Aug 4, 2017 9:03:46 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "test")
public class Users implements java.io.Serializable {

	private String username;
	private String password;
	private byte enabled;
	private String email;
	private Set<UserRoles> userRoleses = new HashSet<UserRoles>(0);
	private Set<UserRoles> userRoleses_1 = new HashSet<UserRoles>(0);

	public Users() {
	}

	public Users(String username, String password, byte enabled, String email) {
		this.username = username;
		this.password = password;
		this.enabled = enabled;
		this.email = email;
	}

	public Users(String username, String password, byte enabled, String email, Set<UserRoles> userRoleses,
			Set<UserRoles> userRoleses_1) {
		this.username = username;
		this.password = password;
		this.enabled = enabled;
		this.email = email;
		this.userRoleses = userRoleses;
		this.userRoleses_1 = userRoleses_1;
	}

	@Id

	@Column(name = "username", unique = true, nullable = false, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 60)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "enabled", nullable = false)
	public byte getEnabled() {
		return this.enabled;
	}

	public void setEnabled(byte enabled) {
		this.enabled = enabled;
	}

	@Column(name = "email", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<UserRoles> getUserRoleses() {
		return this.userRoleses;
	}

	public void setUserRoleses(Set<UserRoles> userRoleses) {
		this.userRoleses = userRoleses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<UserRoles> getUserRoleses_1() {
		return this.userRoleses_1;
	}

	public void setUserRoleses_1(Set<UserRoles> userRoleses_1) {
		this.userRoleses_1 = userRoleses_1;
	}

}
